const menu=document.getElementById("menu"),cartBtn=document.getElementById("cart-btn"),cartModal=document.getElementById("cart-modal"),cartItemsContainer=document.getElementById("cart-items"),cartTotal=document.getElementById("cart-total"),checkoutBtn=document.getElementById("checkout-btn"),closeModalBtn=document.getElementById("close-modal-btn"),cratCounter=document.getElementById("cart-count"),addressInput=document.getElementById("address"),addressWarn=document.getElementById("address-warn");let cart=[];cartBtn.addEventListener("click",function(){updateCartModal(),cartModal.style.display="flex"}),cartModal.addEventListener("click",function(a){a.target===cartModal&&(cartModal.style.display="none")}),closeModalBtn.addEventListener("click",function(){cartModal.style.display="none"}),menu.addEventListener("click",function(a){let b=a.target.closest(".add-to-cart-btn");if(b){const a=b.getAttribute("data-name"),c=parseFloat(b.getAttribute("data-price"));addToCart(a,c)}});function addToCart(a,b){const c=cart.find(b=>b.name===a);c?c.quantity+=1:cart.push({name:a,price:b,quantity:1}),updateCartModal()}function updateCartModal(){cartItemsContainer.innerHTML="";let a=0;cart.forEach(b=>{const c=document.createElement("div");c.classList.add("flex","justify-between","mb-4","flex-col"),c.innerHTML=`
        <div class="flex items-center justify-between"> 
           <div>
            <p class ="font-bold">${b.name}</p>
            <p>Qtd: ${b.quantity}</p>
            <p class= "font-medium mt-2">R$ ${b.price.toFixed(2)}</p>
           </div>


            <button class= "remove-from-cart-btn" data-name="${b.name}">
              Remover
            </button>

    </div>
        `,a+=b.price*b.quantity,cartItemsContainer.appendChild(c)}),cartTotal.textContent=a.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),cratCounter.innerText=cart.length}cartItemsContainer.addEventListener("click",function(a){if(a.target.classList.contains("remove-from-cart-btn")){const b=a.target.getAttribute("data-name");removeItemCart(b)}});function removeItemCart(a){const b=cart.findIndex(b=>b.name===a);if(-1!==b){const a=cart[b];if(1<a.quantity)return a.quantity-=1,void updateCartModal();cart.splice(b,1),updateCartModal()}}addressInput.addEventListener("input",function(a){let b=a.target.value;""!==b&&(addressInput.classList.remove("border-red-500"),addressWarn.classList.add("hidden"))}),checkoutBtn.addEventListener("click",function(){const a=checkRestaurantOpen();if(!a)return void Toastify({text:"Ops o restaurante esta fechado!",duration:3e3,close:!0,gravity:"top",position:"right",stopOnFocus:!0,style:{background:"#ef4444"}}).showToast();if(0===cart.length)return;if(""===addressInput.value)return addressWarn.classList.remove("hidden"),void addressInput.classList.add("border-red-500");const b=cart.map(a=>`${a.name} Quantidade: (${a.quantity})  Preço: R$${a.price} |`).join(" "),c=encodeURIComponent(b);window.open(`https://wa.me/${"12996354928"}?text=${c} Endereço:  ${addressInput.value}`,"_blank"),cart=[],updateCartModal()});function checkRestaurantOpen(){const a=new Date,b=a.getHours();return 18<=b&&22>b}const spanItem=document.getElementById("date-span"),isOpen=checkRestaurantOpen();isOpen?(spanItem.classList.remove("bg-red-500"),spanItem.classList.add("bg-green-600")):(spanItem.classList.remove("bg-green-600"),spanItem.classList.add("bg-red-500"));